### ISSUE TITLE
Search text box missing

### ISSUE THREAD

**Issue by gelidude** [covalition/octopus#18]
The search text box is missing so I can't search in my library. I'm running windows 7 pro with .net framework 4.5

**Comment by romanoza** [comment]
@gelidude Could you please attach some screenshots?

**Comment by MnICHoO** [comment]
Hi, I just installed this application to open and search my old library and encountered the same problem. There is no search text box. Using version 2.0.1.2 on Windows 7 x64 Pro
Here is screenshot how it looks:
![2016-08-26 16_43_18-octopus covalition 2 0 1 2](https://cloud.githubusercontent.com/assets/21263865/18009476/b81f9b3c-6bac-11e6-8b4f-d4a95314347f.png)
