### ISSUE TITLE
New version requires instalation of SharpZipLib on Vista

### ISSUE THREAD

**Issue by zecamigo** [covalition/octopus#22]
Hi there

Help needed here.
I've tried to install Octopus 2.0.1.3 because of previous version bug with search (no search fields appear).
However, still no luck, I'm asked to install  ICSharpCode.SharpZipLib 0.85.5.452 into Global Assembly Cache. I've searched issues here but could find no mention to it. A google search tells me that should be installed in Visual Studio. As a total newbie I've no idea how to do this so just gave up at this point.

I'm using Octopus in Vista. (And was loving it until now :/ )

Thanks for your work and attention.
José Castro

**Comment by romanoza** [comment]
Thank you for your feedback, I'll correct this in the next release.

**Comment by romanoza** [comment]
Corrected

**Comment by zecamigo** [comment]
Great Work! Working fine now! Merry Xmas for me OH OH OH! ;)
