### ISSUE TITLE
How you install this ?

### ISSUE THREAD

**Issue by 7eptem** [covalition/octopus#23]
how do you install this Unable to install or run the application. The application require that assemblyICSharpCode.SharpZipLib version 0.85.5.452 be installed in the Global Assembly Cache. i tried to put ICSharpCode.SharpZipLib.dll anywhere i could think off, still nothing, and is the same with all versions. I use NET Framework 4.5 BTW, any solutions ?

**Comment by romanoza** [comment]
Duplicate #22
