### ISSUE TITLE
Future of Octopus?

### ISSUE THREAD

**Issue by fire-eggs** [covalition/octopus#25]
romanoza -
I've been poking at your Octopus project, and I think it has a lot of potential! I've been reworking some bits (see my fork at [Octopus](http://github.com/fire-eggs/octopus)) and have more ideas in the planning stages.

I wanted to know where you planned to take it from 2.0.1.4.  What would be the best way for me to move this forward without causing you any distress? Did you have any users which might be interested in new updates, or providing feedback?

(reply and we can correspond via email if you prefer)
Thank you,
Kevin aka fire-eggs

**Comment by romanoza** [comment]
@fire-eggs 
Hi Kevin,
I don't have any specific plans regarding this project at the moment. Also, I don't have any list of the current end users nor maintain any type of the user community. You can go with this project whatever way you want, as far as it is compatible with the current Ms-RL license. Enjoy & have fun!

**Comment by fire-eggs** [comment]
I'm cool with the Ms-RL license. I hoped to push this as "Octopus 3.0" as long as you didn't have an issue with it.

Thank you! Don't hesitate to make any requests or suggestions!
Kevin
